# Generated by Django 5.0.6 on 2024-06-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='anonymous@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='anonymous', max_length=80),
        ),
    ]
