# Generated by Django 5.0.6 on 2024-06-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_post_answered_alter_post_author_alter_post_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
