# Generated by Django 5.0.6 on 2024-06-06 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0007_rename_author_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ticket',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
