# Generated by Django 5.0.6 on 2024-06-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0008_post_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='No title question', max_length=50),
        ),
    ]
